alias ls='ls --color=auto'
alias ll='ls -lh'
alias la='ls -A'
alias l='ls -CF'
alias xup='xrdb -merge $HOME/.Xresources'
alias tmux='tmux -2'
alias vim='TERM=tmux-256color nvim.appimage'
alias ivm=vim
alias v=vim
alias nvim=vim
alias vp='find . -name "*.py" -exec nvim.appimage {} \+ '
alias vimrc='vim $HOME/.config/nvim/init.lua'
alias tp='vim /tmp/$(cat /dev/urandom | env LC_CTYPE=C tr -cd 'a-f0-9' | head -c 32).py'
alias ts='vim /tmp/$(cat /dev/urandom | env LC_CTYPE=C tr -cd 'a-f0-9' | head -c 32).sh'
alias bashrc='vim $HOME/.bashrc'
alias wgetrc='vim $HOME/.wgetrc'
alias conkyrc='vim $HOME/.conkyrc'
alias muttrc='vim $HOME/.muttrc'
alias sshconfig='vim $HOME/.ssh/config'
alias xresources='vim $HOME/.Xresources'
alias tmuxconfig='vim $HOME/.tmux.conf'
alias gitconfig='vim $HOME/.gitconfig'
alias gut=git
alias gti=git
alias podcast='mpv --profile=podcast'
alias iptv='mpv --profile=iptv $HOME/.config/mpv/ru.m3u'
alias downloads='cd $HOME/downloads/ && ll ./'
alias tmp='cd /tmp'
alias aliases='vim $HOME/.bash_aliases'
alias make_go_dirs='mkdir src pkg bin cmd'
alias mattdir='cd $HOME/projects/Matthew_Paulton/'
alias docker_remove_containers_exited='docker rm -v $(docker ps -aq -f status=exited)'
alias xp='xprop | grep "WM_WINDOW_ROLE\|WM_CLASS" && echo "WM_CLASS(STRING) = \"NAME\", \"CLASS\""'
alias t='tree'
alias ff='firefox-esr'
alias selact='source $HOME/.virtualenvs/sel_requests/bin/activate'
alias htact='source $HOME/.virtualenvs/httpx_env/bin/activate'
alias mkadventfiles='touch script.py {input,input_sample}.txt'
alias greppy='ll -t | grep --include=\*.py --color=auto -ri'
alias gh='git h'
alias my='cd $HOME/projects/my'
alias yt='cd $HOME/.local/bin && ./spoofdpi'
