alias ls='ls --color=auto'
alias ll='ls -lh'
alias la='ls -A'
alias l='ls -CF'
alias xup='xrdb -merge $HOME/.Xresources'
alias zonasin='cd $HOME/python_proj/test/cableCo/zonASINhunter'
alias newegg='cd $HOME/python_proj/test/cableCo/newegg3'
alias perlsandbox='cd $HOME/sandbox/perl'
alias flasksandbox='cd $HOME/sandbox/flask_PY3'
alias vim='/usr/bin/nvim'
alias vimrc='vim $HOME/.vimrc'
alias bashrc='vim $HOME/.bashrc'
alias wgetrc='vim $HOME/.wgetrc'
alias conkyrc='vim $HOME/.conkyrc'
alias sshconfig='vim $HOME/.ssh/config'
alias xresources='vim $HOME/.Xresources'
alias utube='mpv --profile=youtube'
alias podcast='mpv --profile=podcast'
alias remote='ssh vultrserver'
alias eugene_remote='ssh eugene_host'
alias canadapost='cd $HOME/python_proj/test/CANADAPOST_CA'
alias miamidade='cd $HOME/python_proj/test/miami_dade && ll ./'
alias downloads='cd $HOME/downloads/ && ll ./'
alias tmp='cd /tmp'
alias aliases='vim $HOME/.bash_aliases'
alias car_dealers='cd $HOME/python_proj/test/CAR_DEALERS/'
